version: '3.9'

services:
  backend:
    build:
      context: ./native.backend
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: Server=db,1433;Database=native;User Id=sa;Password=Xyzzy2005!;TrustServerCertificate=True;Encrypt=False
      Cors__AllowedOrigins__0: http://localhost:5173
    depends_on:
      - db
    # Uncomment the following lines to enable hot reload with local files
    # volumes:
    #   - ./native.backend:/src

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:5000
    depends_on:
      - backend
    # Uncomment to enable live editing with local files
    # volumes:
    #   - ./:/app
    #   - /app/node_modules

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Xyzzy2005!
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - db-data:/var/opt/mssql

volumes:
  db-data:
