version: '3.9'

services:
  backend:
    build:
      context: ./native.backend
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: Host=db;Port=5432;Database=native;Username=native;Password=changeme
      Cors__AllowedOrigins__0: http://localhost:5173
    depends_on:
      - db
    # Uncomment the following lines to enable hot reload with local files
    # volumes:
    #   - ./native.backend:/src

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:5000
    depends_on:
      - backend
    # Uncomment to enable live editing with local files
    # volumes:
    #   - ./:/app
    #   - /app/node_modules

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: native
      POSTGRES_USER: native
      POSTGRES_PASSWORD: changeme
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
